In [20]:
import pandas as pd
import numpy as np

data_discover = pd.read_csv(r'Discover Часовые общийCorr59.csv', sep=';', na_values='N', decimal=',')

column_names_discover = ['bx_gsm', 'by_gsm', 'bz_gsm', 'bt', 'proton_density', 'proton_speed', 'proton_temperature']

In [21]:
pd.set_option('future.no_silent_downcasting', True)

def linear_interpolate_gaps(df, column_names, max_gap_length=12):
    for column_name in column_names:
        missing_indices = df[column_name].isnull()
        start_indices = []
        end_indices = []
        
        is_missing = False
        
        for i in range(len(df)):
            if missing_indices[i] and not is_missing:
                start_indices.append(i)
                is_missing = True
            elif not missing_indices[i] and is_missing:
                end_indices.append(i)
                is_missing = False
        
        for start, end in zip(start_indices, end_indices):
            if end - start < max_gap_length:
                if start != 0:
                    y1 = df.loc[start - 1, column_name]
                    y2 = df.loc[end, column_name]
                
                    x = np.arange(start, end)
                    y = np.interp(x, [start - 1, end], [y1, y2])
                
                    df.loc[start:end-1, column_name] = y

    return df

In [22]:
data_discover.iloc[range(1256,1268), [4, 9, 10, 11, 20, 21]]

,bt,bx_gsm,by_gsm,bz_gsm,proton_density,proton_temperature
1256,7.372292,-1.107917,-6.313542,2.603542,17.140000,94458.79167
1257,NaN,NaN,NaN,NaN,NaN,NaN
1258,NaN,NaN,NaN,NaN,NaN,NaN
1259,NaN,NaN,NaN,NaN,NaN,NaN
1260,NaN,NaN,NaN,NaN,NaN,NaN
1261,6.356111,3.811667,3.493889,3.558889,NaN,NaN
1262,5.291833,3.590500,-2.950667,2.032333,12.668710,211530.38710
1263,5.096333,3.712667,-1.952000,2.786500,13.014000,199739.76670
1264,4.498333,3.893667,-1.583167,1.236667,12.688667,199750.13330
1265,4.177000,3.281500,-2.478833,0.323167,12.399833,204589.25000
1266,4.063333,2.967667,-2.554833,-0.603167,11.978167,212267.08330
1267,4.429000,3.358333,-2.777500,-0.538833,11.122500,221002.66670

In [23]:
data_discover_interpolated = linear_interpolate_gaps(data_discover, column_names_discover, max_gap_length=12)

In [24]:
data_discover_interpolated.iloc[range(1256,1269), [4, 9, 10, 11, 20, 21]]

,bt,bx_gsm,by_gsm,bz_gsm,proton_density,proton_temperature
1256,7.372292,-1.107917,-6.313542,2.603542,17.140000,94458.791670
1257,7.169056,-0.124000,-4.352056,2.794611,16.394785,113970.724242
1258,6.965819,0.859917,-2.390569,2.985681,15.649570,133482.656813
1259,6.762583,1.843833,-0.429083,3.176750,14.904355,152994.589385
1260,6.559347,2.827750,1.532403,3.367819,14.159140,172506.521957
1261,6.356111,3.811667,3.493889,3.558889,13.413925,192018.454528
1262,5.291833,3.590500,-2.950667,2.032333,12.668710,211530.387100
1263,5.096333,3.712667,-1.952000,2.786500,13.014000,199739.766700
1264,4.498333,3.893667,-1.583167,1.236667,12.688667,199750.133300
1265,4.177000,3.281500,-2.478833,0.323167,12.399833,204589.250000
1266,4.063333,2.967667,-2.554833,-0.603167,11.978167,212267.083300
1267,4.429000,3.358333,-2.777500,-0.538833,11.122500,221002.666700
1268,4.353167,2.992000,-3.089667,0.048167,13.272000,209176.950000

In [25]:
data_discover_interpolated.to_csv("Discover_с_интреполяцией12_актуальные_данные_до_22.09.2024.csv", sep=';', index=False, encoding='utf-8')